### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [LeonidVlasov/template-jwood#1]
1. `.foto__picture` не стоит писать 100% height и 100% width одновременно для изображений. Так ты искажишь пропорционально любое изображение, что, впринципе, у тебя и произошло.
3. `mailto:` пустой?  и `tel:` для телефона вообще не прописан
4. нет минимальной высоты для главного экрана, поэтому в какой-то момент элементы начинают наезжать друг на друга
5. Что это за стиль ? `Normalize.css` не решил этой проблемы и ты сам дописал ?
```
* {
	box-sizing: border-box;
	cursor: auto;
}
```
6. Удали лишние закомментированные строки в css, html перед ревью
7. `logocontainer` нет такого слова, не называй так странно
8. Обращение к тегам я бы выносил наверх css, а потом уже конкретные к классам. Типо такого, например:
```
h1 {
	font-family: 'Nexa', sans-serif ;
	font-size: 3.75rem;
	text-transform: uppercase;
	color: white;
	margin: 3rem 0;
}
```
9. css import с маленькой поддержкой, ты уверен, что тебе он нужен был тут ?
10. Если шрифт можно подключить через CDN - подключай. Я про `open-sans-light`, он явно там есть. 
11. Вытягивать библиотеку и засовывать в свой файл - не всегда хорошая идея. Особенно с font-awesome, они же и cdn дают и минифицированную версию. И случай может быть, когда тебе надо будет быстро обновить fa до новой версии с их новыми иконками, а ты сейчас даже быстро версию не проверишь.
12. `max-width: 414px`, а может лучше использовать общепринятые брейкпоинты, этот какой-то подозрительный.
13. Контакты ооооочень маленькие на мобильных девайсах
14. Социальные иконки не в круге, а в каких-то овалах.
15. `Scroll down иконка` ты ее сдвигаешь ниже при `:hover`, но таким образом ты и сдвигаешь область где я на нее навел, поэтому бывает ситуация. где я навел, попал в фокус, она анимируется вниз, у меня теряется фокус, она возвращается, я снова в фокусе и она снова по кругу делает всё выше сказанное. Получается бешенство с рывками
16. scroll down резко скачет, без transition
17. А почему импорт шрифтов в конце ??
```
@import url('style1200.css');
@import url('style960.css');
@import url('style768.css');
@import url('style414.css');
@import url('fonts.css');
```

**Comment by LeonidVlasov** [comment]
1. Делал, для того чтобы картинка была всегда одинаковой высоты с текстом (ты потом объяснил что бы избежать искажения надо через беграунд-имг) - убрал высоту.
2. Добавил почту и атрибут тел в href
3. Добавил мин-хайт
4. Не юзаю нормалайз, убрал - курсор-авто
6. В хтмл не нашел, в цсс удалил
7. Переименовал на logobox
8. Перенос на верх
9. Удалил
10. Так он у меня в fonts.css подключен. Этого мало ?
11. Понял, на бокопорил с фонтавесом. скачал мин.цсс их и убрал из fonts.css
12. Изменил на 420пх.
13. Увеличил шрифт
14. Исправил
15. Исправил
16. Исправил
17. Исходил из того, что стили важнее - шрифт менее важен. Поднял в топ фонтс.цсс
